### ISSUE TITLE
The Synchronizing phase is not clear

### ISSUE THREAD

**Issue by elopio** [nimiq-network/core#145]
## New issue checklist

- [x] I have read all of the [`README`](../README.md) 
- [x] I have searched [existing issues](https://github.com/nimiq-network/core/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Browser version(s): Firefox 52.0.1, Ubuntu 17.10
- Reproducible in the testnet?: Yes

#### Expected behavior

A clear explanation of what's going on at each step.
During the synchronization phase, explain that first the blocks need to be fetched before mining starts.

#### Actual behavior

When I first open the betanet there's not much that I can do because I need to wait for the synchronization to finish. However, this is not clearly explained in the UI. 

I see that I start to get connections, and that I'm fetching blocks. For somebody new to blockchain that doesn't mean much. Also, I see the global hashrate and my hashrate in 0, which can make me start wondering if this is my synchronization rate. If it's 0, I will never finish.

#### Steps to reproduce

Clear offline data of the browser, open the betanet.

#### Screenshots

![selection_001 copy](https://user-images.githubusercontent.com/617831/26907803-5fee1bcc-4bb3-11e7-813f-0730e65d5fe3.png)

**Comment by elopio** [comment]
When the sync was done, a small text appeared under the hashrates saying: "At your current hashrate you can expect to mine [...]"

A very simple fix for this could be to use that same space to say something like: "Before you can start mining, all the blocks need to be fetched"

**Comment by styppo** [comment]
We now show more detailed messages during the sync process.
