### ISSUE TITLE
When mining is paused, an ∞ estimate is displayed

### ISSUE THREAD

**Issue by elopio** [nimiq-network/core#146]
## New issue checklist

- [x] I have read all of the [`README`](../README.md) 
- [x] I have searched [existing issues](https://github.com/nimiq-network/core/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Browser version(s): Firefox 52.0.1, Ubuntu 17.10
- Reproducible in the testnet?: Yes

#### Expected behavior

When mining is paused, it's not possible to estimate the number of coins that will be mined.
I think it's better to mention this, instead of an infinite estimate. Something like:

"To get nimiqs, resume mining"

#### Actual behavior

The message "At your current hashrate you can expect to mine 50 Nimiqs every ∞ years." is displayed. 

#### Steps to reproduce

Open the betanet. Pause mining.

#### Screenshots?

![selection_003](https://user-images.githubusercontent.com/617831/26908348-6224fdb2-4bb7-11e7-867d-0c8683000d9a.png)

**Comment by styppo** [comment]
Displaying an infinite estimate is certainly not the best solution. However, simply changing the text will make the Pause/Resume link jump around, which is bad. We'll consider moving the Pause link into the new hashrate control drawer.
