### ISSUE TITLE
It's not possible to copy&paste information from connected peers

### ISSUE THREAD

**Issue by elopio** [nimiq-network/core#148]
## New issue checklist

- [x] I have read all of the [`README`](../README.md) 
- [x] I have searched [existing issues](https://github.com/nimiq-network/core/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Browser version(s): Firefox 52.0.1, Ubuntu 17.10
- Reproducible in the testnet?: Yes

#### Expected behavior

When I move the mouse over one of the peers in the map, I would expect to be able to select it with a click, and then be able to select and copy the information from that peer. For example, in the attached screenshot, I would like to get some information about the nimvim.org host.

#### Actual behavior

The peer information is only visible while my mouse is over it. If I move my mouse in the direction of the information displayed, that information disappears. This is a little unexpected.

So the only way I have to do something with that information is to type it manually, which is not complex in this example, but it gets more complicated when it's an IP or a weirder host name.

#### Steps to reproduce

Go to the betanet.
Move the mouse over one of the peers.
Move the mouse in the direction of that peer information.

#### Screenshots?

![selection_005](https://user-images.githubusercontent.com/617831/26909189-64b0912c-4bbc-11e7-929c-4c1eb1dd5dcf.png)

**Comment by paberr** [comment]
Thanks for all your comments! We will take care of them in the upcoming changes.
(Right now we are working on a major feature, so it will have to wait a few days until that is deployed.)

**Comment by styppo** [comment]
Moved to https://github.com/nimiq-network/miner/issues/3.
