### ISSUE TITLE
Wrong node version listed in README

### ISSUE THREAD

**Issue by rafalstapinski** [nimiq-network/core#151]
## New issue checklist

- [x] I have read all of the [`README`](../README.md) 
- [x] I have searched [existing issues](https://github.com/nimiq-network/core/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

#### Expected behavior

> Works with node 7.10.0

#### Actual behavior

> Does not work with node 7.10.0

#### Steps to reproduce

> Use node 7.10.0, then install dependencies following quickstart

**Comment by styppo** [comment]
Seems to be resolved, see #150

**Comment by bityogi** [comment]
I would suggest using node 7.10.1 instead of 7.10.0

https://nodejs.org/en/blog/vulnerability/july-2017-security-releases/
