### ISSUE TITLE
Obtaining persistent AccountsTree more than once fails

### ISSUE THREAD

**Issue by schrnz** [nimiq-network/core#161]
## Bug report

Calling ```AccountsTree.getPersistent()``` more than once (e.g., in a test) fails with the following error:   
```
OpenError: IO error: lock ./database/accounts/LOCK: already held by process
```

#### Expected behavior

Two references that can be used to interact with the database(s) are returned.

#### Actual behavior

The second instance tries to obtain a lock for the single database, which fails because the process already holds the lock. 

#### Steps to reproduce

See test linked below. 

## Question or Feature Request

Depending on whether we want to have a single or multiple databases, I see the following possibilities:

1. single database:
   - return a singleton object to interact with the underlying db
   - or return new instances that ensure synchronization (e.g., via transactions?)
2. multiple databases:
   - create new database and return new object to handle interaction
   - allow to get a (new?) handler for an existing database

Right now, I am not familiar enough with the code to decide this.

**Comment by paberr** [comment]
This issue still remains even with the JungleDB implementation.
