### ISSUE TITLE
Corrupt Wallet

### ISSUE THREAD

**Issue by Eligioo** [nimiq-network/core#164]
## New issue checklist

- [x] I have read all of the [`README`](../README.md) 
- [x] I have searched [existing issues](https://github.com/nimiq-network/core/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s): IndexedDB Database version 4
- Browser version(s): 58.0.3029.110 (64-bit)
- Devices/Simulators/Machine affected: Lost wallet
- Reproducible in the testnet? (Yes/No): Yes
- Related issues: https://www.reddit.com/r/Nimiq/comments/6h19a8/corrupted_wallet/

#### Expected behavior

> Went to https://nimiq.com/betanet/. Waiting for the browser to initalize everything and waiting to being able to click on the "Connect to Network"-button.

#### Actual behavior

> Yellow loading spinner never went away. Manually deleted my IndexedDB through the Chrome Developers Console and reloaded the page and everything was back to normal. With 0,00 currency of course.

#### Steps to reproduce

> Probably not the step that caused the error but I switched to a different Chrome Profile (CTRL + SHIFT + M) to load my other wallet. Since I deleted the corrupted database I won't be able to attach it to this issue and to be able to find out what caused this error.

#### Crash log? Screenshots? Videos? Sample project?

>Nimiq engine loaded.
cdn.nimiq.com/core/web.js:1923 Uncaught (in promise) TypeError: Cannot read property 'hash' of undefined
at PersistentAccountsTreeStore.key (cdn.nimiq.com/core/web.js:1923)
at PersistentAccountsTreeStore.remove (cdn.nimiq.com/core/web.js:1939)
at AccountsTree._clear (cdn.nimiq.com/core/web.js:3052)
at <anonymous>

## Question or Feature Request

>

**Comment by paberr** [comment]
Thank you for your report! As far as I can see, this problem has been fixed this morning.

**Comment by senikk** [comment]
If its fixed why is this is issue still open?

**Comment by paberr** [comment]
Because I forgot to close it. Thanks for reminding me!
