### ISSUE TITLE
How to get amount of nimiq mined using nodejs client ?

### ISSUE THREAD

**Issue by thomasthiebaud** [nimiq-network/core#166]
## New issue checklist

- [x] I have read all of the [`README`](../README.md) 
- [x] I have searched [existing issues](https://github.com/nimiq-network/core/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s): 1.0.0

## Question or Feature Request

I installed the nodejs client on my dedicated server, and I would like to check the status of my wallet. I found a directory called `database` with the following content

```shell
$:~/Dev/core/database# ls
accounts  blocks  keys  wallet
```
I manually tried to check all of this directory but I found nothing.

How can I see the content of my wallet ?

**Comment by jsappme** [comment]
+1

**Comment by jsappme** [comment]
$.accounts.getBalance($.wallet.address)
            .then(balance => {
                console.log(Nimiq.Policy.satoshisToCoins(balance.value).toFixed(4));
            });

**Comment by thomasthiebaud** [comment]
Where ? I'm using the nodejs client, not the browser.

**Comment by sisou** [comment]
In the index.js, you need to add a listener to the balance-change event that then logs the new balance to the command line.

**Comment by thomasthiebaud** [comment]
Ok, thanks a lot. I will try it.
