### ISSUE TITLE
Accounts tree export without corresponding import functionality

### ISSUE THREAD

**Issue by schrnz** [nimiq-network/core#172]
The Blockchain class allows to export the accounts tree (cf. line [514](https://github.com/nimiq-network/core/blob/3a5bdb848079828ca1086cc253061b028a82a6f0/src/main/generic/consensus/blockchain/Blockchain.js#L514)). However, there is no corresponding import functionality, hence it is hard to, e.g.,  write tests without making assumptions about the particular implementation. Right now, this API is completely unused. I assume the import/export functionality will be needed at some point, so I leave this issue as a reminder that the feature is not ready yet.

**Comment by paberr** [comment]
The API is currently used to generate the checkpoints for the blockchain. So, it is only called manually.

**Comment by schrnz** [comment]
Ah I see, import is done via the ```populate``` method in ```Accounts```.  However, right now this is somewhat inconsistent since the serialization (base64 of serialized node) is done in ```AccountsTree``` and passed back through ```Accounts``` and ```Blockchain```, and the deserialization is done in the ```Blockchain``` b/c ```populate``` expects actual nodes. I would suggest to refactor this to encapsulate the implementation details of export/import in the same class. Also, the ```loadCheckpoint``` method could be retrofitted to utilize a dedicated ```import``` method. 
I could take care of this sometime in the next days.

**Comment by paberr** [comment]
The API will be removed in the upcoming Luna testnet.
