### ISSUE TITLE
Broken verification of AccountsTree

### ISSUE THREAD

**Issue by schrnz** [nimiq-network/core#174]
## Bug report

Right now the ```AccountsTree``` is not verified since   
1. the ```verify``` method is not called properly   
2. the ```verify``` method is broken

Problem 1 is the reason problem 2 never surfaced. You can see [here](https://github.com/nimiq-network/core/blob/3054c28d17aaebdbb35c73e56a2572bf69606412/src/main/generic/consensus/blockchain/Blockchain.js#L529) (and also [here](https://github.com/nimiq-network/core/blob/3054c28d17aaebdbb35c73e56a2572bf69606412/src/main/generic/consensus/account/tree/AccountsTree.js#L260) for the internal helper method that is invoked recursively) that the immediate result of the methods are checked. However, both return a promise on which the ```!``` operator checks for undefinedness, which is not the case. Hence, verification will always succeed without verifying. Additional ```await``` statements will do the job. 

The second problem is the implementation of the ```_verify``` method. [Here](https://github.com/nimiq-network/core/blob/3054c28d17aaebdbb35c73e56a2572bf69606412/src/main/generic/consensus/account/tree/AccountsTree.js#L261) you can see that it is checked whether the prefix of the current subnode equals the prefix of its parent plus ist position in its parent's child list. However, this assumes that child nodes have a complete prefix of the path, but the current implementation only stores the prefix after(!) the parent. Hence, this fails pretty fast for almost all cases. 

#### Steps to reproduce

The branch linked below contains a test case to reproduce the defect.

**Comment by paberr** [comment]
Indeed, you're completely right. Do you want to fix that and file a PR?

**Comment by sisou** [comment]
Was this completely fixed by the merged PR?

**Comment by schrnz** [comment]
Problem 1: definitely yes. The methods are called correctly now. 
Problem 2: probably fixed, too. The point is that the old implementation tried to check that the node is at the correct position by checking whether its prefix matched the prefix of its parent plus the position in the parent's child list (= the nibble). However, we cannot check it that way because we do not have the complete prefix. The whole prefix to a certain node is only obtained by combining all prefixes and position nibbles on the way down. The current implementation only checks that nodes are linked as the correct child node. However, this should transitively ensure that all the nodes are at the correct position. At least that's the idea.
