### ISSUE TITLE
Decide if we should use Flow for static type checking 

### ISSUE THREAD

**Issue by RobinLinus** [nimiq-network/core#181]
Should we use https://flow.org/ ? It is a static type checker for JS. Looks like we could use it to introduce a "more statically" typed system without introducing a strict dependency into our tool stack.

**Comment by mar-v-in** [comment]
Flow uses non-standard-compatible annotations that have to be compiled away (with babel or sth like that). Although it seems to be possible to use standard compliant comments ([see here](https://flow.org/blog/2015/02/20/Flow-Comments/)), these are very ugly IMHO. A short test revealed that Flow would require us to rewrite a portion of our code, as it is not able to check our perfectly valid code. So I would consider this more like a TypeScript-alternative.

With [JSDoc](http://usejsdoc.org/) we can annotate methods like with JavaDoc (to create a full API documentation from source code) and at the same time annotate types in a way static type checkers can verify them. This is natively supported by [Google Closure Compiler](https://developers.google.com/closure/compiler/) (which even applies type-specific optimizations) and many development tools (IDEs/Text Editors). There is also [typelint](https://github.com/yarax/eslint-plugin-typelint), which is a plugin for eslint that does type checking based on JSDoc.

I consider JSDoc a better alternative

**Comment by miclaus** [comment]
For the documentation, you could try documentation.js also:
https://github.com/documentationjs/documentation

With Flow you don't require a transpiler as opposed to TypeScript.

**Comment by mar-v-in** [comment]
Thanks for the link to documentation.js

Re Flow: according to their own [installation instructions](https://flow.org/en/docs/install/) the first step you need to do to use Flow is to setup their "compiler" (either the babel plugin or the seperate tool). [This page](https://flow.org/en/docs/types/interfaces/) shows a lot of Flow features that I am 100% sure will cause syntax errors once run in a normal JavaScript environment...

**Comment by miclaus** [comment]
@mar-v-in yeah there is a [transform-flow-strip-types](https://babeljs.io/docs/plugins/transform-flow-strip-types/) which is also included within `babel-preset-react` if you were to be using React.

```cli
babel-preset-react@6.16.0
│ ├── babel-plugin-transform-flow-strip-types@6.18.0
```

**Comment by deniss-muhla** [comment]
If JS code will be used without compilation then Flow will break it. If it will go thru babel anyway then will be more benefit when trouble.
