### ISSUE TITLE
Microsoft Edge: Object doesn't support property or method 'generateCertificate'

### ISSUE THREAD

**Issue by Eric-Machinas** [nimiq-network/core#182]
## New issue checklist

- [x] I have read all of the [`README`](../README.md) 
- [x] I have searched [existing issues](https://github.com/nimiq-network/core/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s):
- Browser version(s): Microsoft Edge 38.14393.1066.0
- Devices/Simulators/Machine affected:
- Reproducible in the testnet? (Yes/No): Yes
- Related issues:

#### Expected behavior

> testnet should initialise

#### Actual behavior

> does not initialise

#### Steps to reproduce

> open microsoft edge, go to testnet, does not initialise

#### Crash log? Screenshots? Videos? Sample project?

Unhandled promise rejection TypeError: Object doesn't support property or method 'generateCertificate'
babel-runtime.js (1001,11)
"Unhandled promise rejection"

![screenshot_062117_111218_am](https://user-images.githubusercontent.com/12857082/27376914-c8b49698-5673-11e7-92cd-002a7b824b8e.jpg)

**Comment by styppo** [comment]
`RTCPeerConnection.generateCertificate()` is not used anymore (#259).
