### ISSUE TITLE
Inconsistent implementation of AccountTree.clear

### ISSUE THREAD

**Issue by schrnz** [nimiq-network/core#186]
## Bug report

When a tree is cleared, not only all branch and terminal nodes but also the root node is cleaned and no new root node is generated. Hence, when trying to interact with the tree afterwards, it will fail because the root node cannot be obtained.

#### Expected behavior

A new root node is present and the tree can be used as usual.

#### Actual behavior

No new root node is generated, but methods fail because they assume its presence. 

#### Steps to reproduce

Run the test linked below. 

#### Crash log? Screenshots? Videos? Sample project?

Sample crash log:
```
Failures:
1) AccountsTree can clear and resume from a cleared tree
  Message:
    Failed: Cannot read property 'serialize' of undefined
  Stack:
    TypeError: Cannot read property 'serialize' of undefined
        at AccountsTree._export (/home/oliver/Projects/Nimiq/core/src/main/generic/consensus/account/tree/AccountsTree.js:318:43)
```

This trace is generated by and can reproduced using the test linked below.
The crash occurs since the root node is ```undefined```. 
 
## Feature Request

The underlying problem is that implicitly you would assume from the ```clear``` method that it leaves the tree in the initial state. However, the initial state is defined by the constructor which explicitly ensures the existence of root key and root node. Hence, in order to be consistent, the ```clear``` method needs to be implemented in a way that also ensures the initalization. However, it is important to ensure that it is compatible with the  ```populate``` method, which fills the tree from a dump.

**Comment by styppo** [comment]
AccountsTree.clear() has been removed entirely.
