### ISSUE TITLE
Persistent acc tree storage: broken root key storage (node test only)

### ISSUE THREAD

**Issue by schrnz** [nimiq-network/core#188]
## Bug report

The persistent account tree does not find its own root when tested via jasmine (node). It works, however, when tested directly in the browser (gulp test). Consequently, a crash occurs since many operations recursively start at the root node, which is undefined in this case. This might be an issue with the different implementations of the IndexDB API.

#### Expected behavior

For local and browser tests, the persistent account tree storage should be able to find the root node stored under its hash. 

#### Actual behavior

Requesting the root node using its hash yields ```undefined```. 

#### Steps to reproduce

See test below. Since #161 prevents us from testing persistent acc tree storage in general, you need to uncomment [line 28](https://github.com/nimiq-network/core/blob/2444a603b469c7712bc03c78541f06c66610e23c/src/test/specs/generic/consensus/accounts/AccountsTree.spec.js#L28) and restrict yourself to a single test (e.g., via ```fit```)

**Comment by paberr** [comment]
This issue should be fixed with out JungleDB implementation.
