### ISSUE TITLE
Auto reconnect

### ISSUE THREAD

**Issue by senikk** [nimiq-network/core#190]
## New issue checklist

- [x] I have read all of the [`README`](https://github.com/nimiq-network/core/blob/master/README.md) 
- [x] I have searched [existing issues](https://github.com/nimiq-network/core/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s):
- Browser version(s): Chrome 59.0.3071.115 (OS X)
- Devices/Simulators/Machine affected: MacBook Pro
- Reproducible in the testnet? (Yes/No): Yes
- Related issues:

#### Expected behavior

> Auto reconnect if the computer have been to sleep

#### Actual behavior

> Manually needing to click on a link to reconnect

#### Steps to reproduce

> Put your laptop to sleep a small amount of time and open up and go to the https://nimiq.com/betanet/ tab, you now have to manually click on an link to get it started again.

**Comment by sisou** [comment]
Will be fixed in the Luna testnet release (#232).

**Comment by styppo** [comment]
Fixed in cf845b6afab206174c414a2eeb1a0bc48752afe3 (#232)
