### ISSUE TITLE
Nimiq Blockchain Cockpit allows double initialization

### ISSUE THREAD

**Issue by paberr** [nimiq-network/core#200]
## New issue checklist
When using the create/load wallet button in the blockchain cockpit twice, the core is initialized twice as well. This can (and most likely does) yield errors.

## Proposed solution
Do not allow initialization twice *and* make that visible in the UI by disabling the buttons.
Do not forget to reenable the buttons where appropriate (perhaps when an error occurs).

@Aschen @sisou @happyrobotstudio If someone of you wants to have a look at it, this would be amazing!

**Comment by Aschen** [comment]
Hi there !
I don't have a lot of time this day, I will figure out something after the summer if no one does meanwhile
