### ISSUE TITLE
Miner continues work on stale block when new transaction arrives

### ISSUE THREAD

**Issue by tomkha** [nimiq-network/core#205]
I glanced over Miner.js code and as far as I understood it restarts mining every time a new transaction arrives to the head block:

`this._mempool.on('transaction-added', () => this._startWork());`

One the other hand the previously called _mine method still continues to recursively call itself with an old block content. It only terminates when the blockchain head changes.
```
    async _mine(block, buffer) {
        // Abort mining if the blockchain head changed.
        if (!this._blockchain.headHash.equals(block.prevHash)) {
            console.warn('Blockchain head changed, exiting mine()');
            return;
        }
```
Does mining a block with an outdated list of transactions make sense?

**Comment by styppo** [comment]
Probably not in vain but not what we intended. Good catch!

Indeed, the _mine() function will continue working on a block that does not include the new transaction (which is still a valid block, but with potentially less profit), but it will also start working on a block that includes the transaction. The intended behaviour was to abort mining the stale block and start working on a new block that includes the transaction.

The short term fix will be to abort mining the stale block as intended. We will have to figure out what the exact final behaviour will be.
