### ISSUE TITLE
Alpha Cockpit: All transactions displayed have the same receiver and value per block

### ISSUE THREAD

**Issue by sisou** [nimiq-network/core#210]
## New issue checklist

- [x] I have read all of the [`README`](https://github.com/nimiq-network/core/blob/master/README.md) 
- [x] I have searched [existing issues](https://github.com/nimiq-network/core/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s): 
- Browser version(s): Chrome 59
- Devices/Simulators/Machine affected: PC
- Reproducible in the testnet? (Yes/No):  Yes
- Related issues: -

#### Expected behavior
Transaction information displayed in the Mempool and the blocklist display correct reciever address and value

#### Actual behavior
All transactions per block and per mempool display the same receiver address and value

#### Steps to reproduce
Open the alpha cockpit

#### Crash log? Screenshots? Videos? Sample project?
![image](https://user-images.githubusercontent.com/1828163/28581930-fc39d3a6-7163-11e7-8e75-ef3d15337a97.png)

The actual data is this:
![image](https://user-images.githubusercontent.com/1828163/28581967-1de4b412-7164-11e7-9237-6f9853254ee4.png)

## Question or Feature Request
I found it is because the "var" in the for loops in `_mempoolChanged` and `_headChanged` functions (https://github.com/nimiq-network/core/blob/betanet/clients/browser/index.html#L516 and https://github.com/nimiq-network/core/blob/betanet/clients/browser/index.html#L435). The `var` makes the `tx` variable be assigned to the outer function and subsequently overwrites every other loop run's `tx` variable.

I found that changing `for(var tx of ...` to `for(let tx of ...` fixes it. However, I don't know if it is save to use `let`?

**Comment by paberr** [comment]
Actually, we use `for (const ... of ...)` everywhere else. So, using that should be definitely save.
The scoping of `let` and `const` should also be as expected (in contrast to `var`).

**Comment by mar-v-in** [comment]
@paberr the reason we don't use it there is that the file is not transpiled by babel, and some older but still used browsers have problems with `const`/`let`

**Comment by sisou** [comment]
@mar-v-in that's what I meant. The index.html is not babelfied.

**Comment by styppo** [comment]
Just iterate over the transactions array with `for(var i = 0; ... )`.

**Comment by paberr** [comment]
@mar-v-in On the other hand, it looks like all browsers supporting ES6 classes also support `const` and `let`. ([Browser Support](https://caniuse.com/#search=es6))

**Comment by mar-v-in** [comment]
@paberr Except Safari 9, which was one of the browsers we used for testing. We could just drop support for Safari 9 if that gives us any valueable benefit, but using `transactions.forEach` seems to be the better option IMHO

**Comment by paberr** [comment]
@mar-v-in I agree that `forEach` seems to be the better way 👍
