### ISSUE TITLE
Not Connecting to the TestNet after reaching over mining 1000 coins.

### ISSUE THREAD

**Issue by Kerni7** [nimiq-network/core#212]
## New issue checklist

- [x] I have read all of the [`README`](https://github.com/nimiq-network/core/blob/master/README.md) 
- [x] I have searched [existing issues](https://github.com/nimiq-network/core/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s):
- Browser version(s):
- Devices/Simulators/Machine affected:
- Reproducible in the testnet? (Yes/No): 
- Related issues:

#### Expected behavior

> ... Should connect to the betanet in the chrome browser.

#### Actual behavior

> ... I used chrome browser and I am using a high speed internet connection but the wallet will not connect to the testnet network. So I used mozila firefox browser and the nimiq new wallet worked so It is not the internet connection. It is the network preventing me from connecting because I have over 1202 nimiq coins. I have been using other computers to mine for me so I have been transfering the coins to one wallet. So I want to know if you guys block my wallet just because of too much transfers and a high coin count.

#### Steps to reproduce

> ... Just put my Wallet Number in the Betanet and wait for it to load. (I tried to send multiple transactions into to the account in the same hour)

#### Crash log? Screenshots? Videos? Sample project?

>... Wallet Number: 14951CC94EE586A01E25518E412181FE9AB3530B
![image](https://user-images.githubusercontent.com/30509115/28721995-c7ad85cc-7377-11e7-919d-a84ac5eae252.png)

## Question or Feature Request

> Can you guys fix it?

**Comment by danimoh** [comment]
Hello Kerni7.

We do not block any accounts and there is no limit on the coins one can have.
Probably the local database got corrupted (this can happen for example if the synchronization process gets interrupted).

You can check for error messages in the developer console (Ctrl+Shift+I).

Please also check whether the wallet app (nimiq.com/wallet) works fine for you.

Kind regards,
Daniel

**Comment by styppo** [comment]
As @danimoh stated, this doesn't have to do anything with the number of coins you have. Looks like a network connectivity issue, try refreshing your browser window.

**Comment by Kerni7** [comment]
Yeah it works but it is only connecting to on peer right now. Also is there any way to see my previous cashlink transactions if you did not copy the cashlink.
