### ISSUE TITLE
WebCrypto is much slower than fast-sha256

### ISSUE THREAD

**Issue by tomkha** [nimiq-network/core#220]
It looks like native WebCrypto performance is very poor. I simply commented few lines in browser/crypto/CryptoLib.js to fallback to fast-sha256 implementation and the hashrate became 20 times higher.

**Comment by mar-v-in** [comment]
Performance of WebCrypto and fast-sha256 depends on the browser used.

However mainnet won't use sha256 anyway. PoW will be based on cuckoo cycle. This will be implemented using WebAssembly. Even if we'd continue to use sha256 for anything, it would be done using WebAssembly, which should faster than fast-sha256 _and_  WebCrypto in all browsers.
