### ISSUE TITLE
Private Network

### ISSUE THREAD

**Issue by SalmanHaider5** [nimiq-network/core#224]
<h3>Private Network</h3>
Can we create private network using Nimiq through browser?? If yes, how can we create?? If no, can we connect to any other network except Testnet??

**Comment by paberr** [comment]
Technically it is possible to set up your own private network.
We are doing the same for testing our new code in action.

However, we currently do not offer any browser interface to do so.
The only option would be to adjust the seed nodes in the PeerAddresses.js manually, compile the code, run your own seed node and so on...
