### ISSUE TITLE
Could BetaNim Please Be Worth Something

### ISSUE THREAD

**Issue by ninja25538** [nimiq-network/core#230]
I'm very excited for the Nimiq main net and have been closely following the betanet. However, I recently learned that all BetaNim are going to be worthless when the main net comes out. Would you please make a small exchange similar to the NET to NIM exchange right before the main net is released. It could be anything like maybe 1000 BetaNim for 1 Nim but still, at least my processing power wouldn't have been wasted. Also would you mind being more detailed in the white paper, it would be more useful to understand how this works.

**Comment by sisou** [comment]
No. It's testnet coins and always will be. They are only worth something if you find somebody to buy them from you.

The BetaNim will be reset at the end of November with the release of Luna testnet.

(You can always keep the old betanet active, but I doubt that it will bring you anything.)
