### ISSUE TITLE
verify.c gyp ERR! build error

### ISSUE THREAD

**Issue by jsappme** [nimiq-network/core#237]
clients\nodejs> yarn

gives me the following on windows 10, any idea why?

```
verify.c
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\herve\OneDrive\Documents\GitHub\nimiq\clients\nodejs\node_modules\nimiq
```

**Comment by sisou** [comment]
Check this todo list for Windows:
https://github.com/nodejs/node-gyp#on-windows

**Comment by jsappme** [comment]
thanks soren for your help. I checked this todo list and sucessfully installed 

`npm install --global --production windows-build-tool`

but I am still getting the same error. node-gyp seems to run good until it reaches verify.c 

I am using Windows 10 Pro and I also installed Visual Studio 2017

**Comment by jsappme** [comment]
it's working with `npm i` so I will use this until it's solved

**Comment by jsappme** [comment]
Working Fix made locally

Change line 4 in src/native/nimiq_native.c to:
`
#if defined(_WIN32)
#include <winsock2.h>
#pragma comment(lib, "Ws2_32.lib")
#else
#include <arpa/inet.h>
#endif
