### ISSUE TITLE
Docker images start fail, core/dist/nimiq_node can't import

### ISSUE THREAD

**Issue by Azard** [nimiq-network/core#246]
## New issue checklist

- [x] I have read all of the [`README`](https://github.com/nimiq-network/core/blob/master/README.md) 
- [x] I have searched [existing issues](https://github.com/nimiq-network/core/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s):
- Browser version(s):
- Devices/Simulators/Machine affected:
- Reproducible in the testnet? (Yes/No): 
- Related issues:

#### Expected behavior

Docker images run success

#### Actual behavior

Nimiq NodeJS Client starting (host=nimiq.skypool.org, port=8080, miner=true, passive=false)
Pool of size larger than 1 requires WebWorker support.
trying binaryen method: native-wasm
asynchronously preparing wasm
binaryen method succeeded.
[D 19:26:21] WebSocketConnector: WebSocketConnector listening on port 8080
[I 19:26:21] Node: Wallet initialized for address NQ48 8CKH BA24 2VR3 N249 N8MN J5XX 74DB 5XJ8.
{ Error: Cannot find module '/core-release/dist/nimiq_node'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at new MinerWorkerPool (/core-release/dist/node.js:1:223898)
    at Miner (/core-release/dist/node.js:1:205625)
    at __dirname (/core-release/clients/nodejs/index.js:49:19)
    at <anonymous> code: 'MODULE_NOT_FOUND' }

#### Steps to reproduce

docker build \
  --build-arg DOMAIN=nimiq.skypool.org \
  --build-arg BRANCH=release \
  --build-arg WALLET_SEED=<XXX> \
  --build-arg KEY=/etc/letsencrypt/live/skypool.org/privkey.pem \
  --build-arg CRT=/etc/letsencrypt/live/skypool.org/fullchain.pem \
  --build-arg PORT=8080 \
  -t nimiq .

docker run -d -p 8080:8080 -v /etc/letsencrypt/:/etc/letsencrypt/ --name "nimiq" nimiq

It seems `MinerWokerPool.js` require a WebAseembly file as a JS file

**Comment by sisou** [comment]
I think you don't need to run `npm install` in src. I think the docker file is only missing a line where it should run it in the client/nodejs folder.

**Comment by cinooo** [comment]
changing the line to: 

`RUN cd /core && npm install && npm run build && npm run prepare`

**Comment by Azard** [comment]
@cinooo Thanks !

**Comment by cinooo** [comment]
No problems, did you have to copy your keys into the docker image as well?

**Comment by styppo** [comment]
Closed via ad5f5f0483650217d1e32e80f55a81f61045ad3a
