### ISSUE TITLE
Does not compile on Windows

### ISSUE THREAD

**Issue by d-krause** [nimiq-network/core#247]
## New issue checklist

- [ x] I have read all of the [`README`](https://github.com/nimiq-network/core/blob/master/README.md) 
- [ x] I have searched [existing issues](https://github.com/nimiq-network/core/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s): Master b24310f
- Browser version(s): N/A
- Devices/Simulators/Machine affected: Windows NodeJS Client
- Reproducible in the testnet? (Yes/No):  Yes

## Bug report
Does not compile on Windows Server 2016

#### Crash log? Screenshots? Videos? Sample project?
Build Log
`PS C:\Users\dkrause\nimiq\core> npm install
> nimiq@1.0.0 install C:\Users\dkrause\nimiq\core
> node-gyp rebuild
C:\Users\dkrause\nimiq\core>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  argon2.c
  blake2b.c
  core.c
  encoding.c
  nimiq_native.c
  ref.c
..\src\native\nimiq_native.c(9): fatal error C1083: Cannot open include file: 'arpa/inet.h': No such file or directory [C:\Users\dkrause\nimiq\c
ore\build\nimiq_node.vcxproj]
  fe.c
  ge.c
  keypair.c
  memory.c
  sc.c
  sha512.c
  sign.c
  verify.c
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1`

## Working Fix made locally
Change line 4 in src/native/nimiq_native.c to:
`
#if defined(_WIN32)
    #include <winsock2.h>
    #pragma comment(lib, "Ws2_32.lib")
#else
    #include <arpa/inet.h>
#endif

`

**Comment by jsappme** [comment]
+1
