### ISSUE TITLE
Cashlink UX and wrong amount when re-used

### ISSUE THREAD

**Issue by sisou** [nimiq-network/core#279]
A user on Discord reported two issue with cashlinks, one UX and one UI:

1. Receive cashlink from someone and accept NIM
2. Look in a transaction history (block explorer) from which address the NIM came
3. **Send (different amount of) NIM back to that address, thinking it is the original sender's address**
4. It's not, original sender does not receive the NIM
5. Visit the initial cashlink again to receive back the NIM sent in 3.
6. **Cashlink shows the original cashlink NIM amount, instead of the actual funds**

**Comment by styppo** [comment]
Moved to https://github.com/nimiq-network/wallet/issues/2.
