### ISSUE TITLE
nimiq luna testnet doesn't load in Chrome - Ubuntu

### ISSUE THREAD

**Issue by GrossBetruger** [nimiq-network/core#293]
the luna testnet stays stuck on the loading graphics of the miner (https://nimiq.com/miner/).
it works perfectly on firefox on the same machine

**messages in browser console**:
Client lacks native support for async
Failed to load resource: the server responded with a status of 404 ()

Version details: 

**OS**: 
uname -a: 
Linux myname-GT70-2PC 4.4.0-101-generic #124-Ubuntu SMP Fri Nov 10 18:29:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

lsb_release -a:
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

**Browser**:

Google Chrome | 54.0.2840.100 (Official Build) (64-bit)
-- | --
Revision | ed651c97177b2ac846b27f62bb8efed6dac0f90b-refs/branch-heads/2840@{#833}
OS | Linux
JavaScript | V8 5.4.500.41
Flash | 28.0.0.126
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.100 Safari/537.36
Command Line | /usr/bin/google-chrome-stable --wm-user-time-ms=1457422606 --flag-switches-begin --enable-tab-audio-muting --flag-switches-end --disable_transparent_visuals --window-depth=24 --x11-visual-id=70

**Comment by sisou** [comment]
As per https://caniuse.com/#feat=async-functions, Chrome gained support for async functions only in version 55. So please update your Chrome (you can follow a guide such as this: https://www.itzgeek.com/how-tos/linux/ubuntu-how-tos/install-google-chrome-on-ubuntu-16-04.html).

**Comment by paberr** [comment]
Since we have a new testnet running, I will close this issue.
Should the problem persist in our new testnet despite updating Chrome, feel free to reopen.
