### ISSUE TITLE
Error: Primitive: Invalid length from docker logs

### ISSUE THREAD

**Issue by refex** [nimiq-network/core#314]
- [ x] I have read all of the [`README`](https://github.com/nimiq-network/core/blob/master/README.md) 
- [x ] I have searched [existing issues](https://github.com/nimiq-network/core/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s): 
- Browser version(s): backbone node
- Devices/Simulators/Machine affected: 

#### Expected behavior
nodejs miner starts running

#### Actual behavior
I cal build a docker image, run it but can't mine.

#### Steps to reproduce
 - git clone nimiq/core repo and checkout release branch
 - `docker build --build-arg DOMAIN=cryptoproject.cf --build-arg BRANCH=release --build-arg WALLET_SEED="NQ29 B6QB 7XQF KP3T YXFA P8C9 CF4B LC3V LXCB" --build-arg KEY=/etc/letsencrypt/live/cryptoproject.cf/privkey.pem --build-arg CRT=/etc/letsencrypt/live/cryptoproject.cf/fullchain.pem -t nimiq .`
 - `docker run -d -p 8080:8080 -v /etc/letsencrypt/:/etc/letsencrypt "nimiq" nimiq`
 - `docker logs --follow <container id>`
 
#### This is the actual error message:

> Nimiq NodeJS Client starting (host=cryptoproject.cf, port=8080, miner=true, passive=false)
> Error: Primitive: Invalid length
>     at PrivateKey.Primitive (/core-release/dist/node.js:1:33328)
>     at PrivateKey (/core-release/dist/node.js:1:34897)
>     at Function.unserialize (/core-release/dist/node.js:1:35060)
>     at Function.unserialize (/core-release/dist/node.js:1:36809)
>     at Function.fromHex (/core-release/dist/node.js:1:37027)
>     at Function.load (/core-release/dist/node.js:1:257615)
>     at __dirname (/core-release/clients/nodejs/index.js:46:52)
>     at anonymous
>

**Comment by paberr** [comment]
The wallet seed you entered is not a valid wallet seed. In fact, it is a wallet address.
The wallet seed represents your key pair including the private key, while the wallet address is only a representation of your public address.

In the current release version, you can export your key pair by calling `.dump()` on the Wallet object.
This will be changed in newer versions.
For more information about exporting your wallet seed, I recommend you to join our Telegram channel or Discord.
