### ISSUE TITLE
This node.js client is working?

### ISSUE THREAD

**Issue by flying01** [nimiq-network/core#318]
I am running node.js client on a linux host, returning a row of data every minute as follows: 

> [I 21:31:10] Node: Connected to wss: //dev.nimiq-network.com:8080

  there is nothing else Information, it is working?

**Comment by flying01** [comment]
now , is more information:

> [W 21:50:43] Network: Connection to wss://dev.nimiq-network.com:8080 failed
[W 21:50:43] WebSocketConnector: Connection to wss://dev.nimiq-network.com:8080 succeeded after timeout - closing it

**Comment by sisou** [comment]
It is working, but you are using the `master` branch, so you are in the staging (alpha) network, and not the regular testnet. Switch to the `release` or `luna` branch to connect to the testnet.

**Comment by flying01** [comment]
Switch to testnet using this link?

https://github.com/nimiq-network/core/archive/luna-v3.zip

**Comment by sisou** [comment]
Better use current version: https://github.com/nimiq-network/core/archive/luna.zip
