### ISSUE TITLE
npm  WARN lifecycle nimiq@1.0.0

### ISSUE THREAD

**Issue by flying01** [nimiq-network/core#321]
node -v: 9.4.0
npm -v: 5.6.0
OS: debian

when i run:  sudo npm install,

show me this WARN message:

> npm WARN lifecycle nimiq@1.0.0~install: cannot run in wd %s %s (wd=%s) nimiq@1.0.0 node-gyp rebuild /home/pi/core-luna
> npm WARN lifecycle nimiq@1.0.0~prepare: cannot run in wd %s %s (wd=%s) nimiq@1.0.0 gulp build-node /home/pi/core-luna

i don't known what  this message means, is the installation successful?

**Comment by Dallo** [comment]
How were you able to resolve this?
