### ISSUE TITLE
MultiSigWallet should be able to sign independently of the order of the provided public keys

### ISSUE THREAD

**Issue by danimoh** [nimiq-network/core#334]
Changing the order of provided public keys in PartialSignature.create changes the signature which ideally should not be the case.

This behavior can be observed e.g. by swapping the public keys in 
```
const partialSignature1 = wallet1.signTransaction(transaction, [keyPair1.publicKey, keyPair2.publicKey],
            aggregatedCommitment, commitmentPair1.secret);
```
in test `MultiSigWallet can create a signed transaction`

**Comment by styppo** [comment]
Closed in d7e292d07f078c67b4ba9ddf57fc39c1e84d9615
