### ISSUE TITLE
MainNet Date

### ISSUE THREAD

**Issue by goktugyil** [nimiq-network/core#345]
What is the estimated date for MainNet launch?

And what can the community do to help out at this stage?

**Comment by xiaomingfuckeasylife** [comment]
be patient would be a good start .

**Comment by styppo** [comment]
Please wait for an official announcement regarding the MainNet launch date. Refer to our community channels ([Telegram](https://t.me/joinchat/AAAAAEJW-ozFwo7Er9jpHw), [Discord](https://discord.gg/cMHemg8), [Medium](https://medium.com/nimiq-network)) for further updates.
