### ISSUE TITLE
Private Blockchain

### ISSUE THREAD

**Issue by SalmanHaider5** [nimiq-network/core#353]
Why we are unable to create private blockchain? Or how can we create it? I need private blockchain instead of public. Is nimiq supported or possible in near future?

**Comment by tomkha** [comment]
If you simply want a clean blockchain with the same genesis block you'll just need to replace peer addresses in PeerAddressBook.js (or PeerAddresses.js, depends on the branch)

**Comment by AndrewBogushevich** [comment]
I guess question was about privacy like in monero/zcash. And I guess it's not an option for nimiq because main goals/advantages of nimiq are fast sync, instant transactions and low entry lvl. IMO privacy solution has bad connection to all of this thing.

**Comment by paberr** [comment]
In case the question as related to creating your own private testnet, `GenesisConfig.js` is now the file to look for.
