### ISSUE TITLE
Responsible disclure procedure

### ISSUE THREAD

**Issue by jgraef** [nimiq-network/core#354]
I found an issue with your implementation. I was actually looking for bugs that qualify for the bug-bounty, but I don't think this issue qualifies for it, since there is no immediate attack scenario. Nevertheless I'm not sure, if it would be sensible to publicly disclose it. Is there an email address where I can send my bug report?

**Comment by sisou** [comment]
Hello!
Thank you for your time and respect for responsible bug disclosure. You can write your report to info@nimiq.com, or contact any of the team on Discord or Telegram.

Although the bug may not qualify 100% for the bug bounty, we still keep our options open to reward bugs outside of the hackerone program.

Thank you!

**Comment by styppo** [comment]
Hi Janosch, thank you for the report. We are reviewing it now and will be in touch with you shortly.
