### ISSUE TITLE
does your code works on windows?

### ISSUE THREAD

**Issue by aminnagpure** [nimiq-network/core#358]
iam quite a good developer on nodejs
but the libraries r not compiling, some have missing header files and some misplaced files

in the src/native

could not compile, does it work on windows 10?
or linux only

errors iam getting are

..\src\native\sha256.c(136): warning C4244: '=': conversion from 'unsigned __int64' to 'BYTE', possible loss of data [E:\angularpractise\core\build\nimiq_node.vcxproj]
..\src\native\sha256.c(137): warning C4244: '=': conversion from 'unsigned __int64' to 'BYTE', possible loss of data [E:\angularpractise\core\build\nimiq_node.vcxproj]
..\src\native\sha256.c(138): warning C4244: '=': conversion from 'unsigned __int64' to 'BYTE', possible loss of data [E:\angularpractise\core\build\nimiq_node.vcxproj]
..\src\native\sha256.c(139): warning C4244: '=': conversion from 'unsigned __int64' to 'BYTE', possible loss of data [E:\angularpractise\core\build\nimiq_node.vcxproj]
..\src\native\sha256.c(140): warning C4244: '=': conversion from 'unsigned __int64' to 'BYTE', possible loss of data [E:\angularpractise\core\build\nimiq_node.vcxproj]
..\src\native\sha256.c(141): warning C4244: '=': conversion from 'unsigned __int64' to 'BYTE', possible loss of data [E:\angularpractise\core\build\nimiq_node.vcxproj]
..\src\native\sha256.c(142): warning C4244: '=': conversion from 'unsigned __int64' to 'BYTE', possible loss of data [E:\angularpractise\core\build\nimiq_node.vcxproj]
  fe.c
  ge.c
  keypair.c
  memory.c
  sc.c
  sha512.c
  sign.c
  verify.c
e:\angularpractise\core\src\native\sha256.h(20): error C2371: 'WORD': redefinition; different basic types (compiling source file ..\src\native\nimiq_native.c) [E:\angularpractise\core\build\nimiq_node.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\shared\minwindef.h(159): note: see declaration of 'WORD' (compiling source file ..\src\native\nimiq_native.c)

**Comment by jeffesquivels** [comment]
Hi @aminnagpure,

Yes, this is a known issue, I have prepared a fix but only have a Windows 8.1 machine to test on, could you please test it on your setup?

The fix is in the [`jeff/windows_fixes`](https://github.com/nimiq-network/core/tree/jeff/windows_fixes) branch.

Thanks!

**Comment by deniss-muhla** [comment]
Hi @jeffesquivels,
Have tested this branch. Works OK on windows.

**Comment by jeffesquivels** [comment]
Hi @deniss-muhla,

Great! Thanks for the help, we are going to merge the fixes then.

Regards,
