### ISSUE TITLE
Proper Installation Instructions on Centos 7

### ISSUE THREAD

**Issue by Cavain** [nimiq-network/core#376]
Hello,

I followed the installation after reading your readme file. But that file is not complete I believe. I'm trying to install nimiq on Centos 7 server, what is proper installation procedure including SSL and domain integration?

Thank you.

**Comment by paberr** [comment]
SSL/domain integration can easily be done by relying on Let's Encrypt.
Apart from that, it is possible to run a node in WS mode without the need for certificates.
