### ISSUE TITLE
README incorrect for node start instrcutions

### ISSUE THREAD

**Issue by Crunklin** [nimiq-network/core#377]
Question or Feature Request

> README for Node.js client  shows:

node index.js --host=HOSTNAME --port=PORT --cert=SSL_CERT_FILE --key=SSL_KEY_FILE [options]

It should now read:

nimiq --host=HOSTNAME --port=PORT --cert=SSL_CERT_FILE --key=SSL_KEY_FILE [options]

Simple, but very confusing for someone trying to setup node via linux and following instructions on Github page.

**Comment by styppo** [comment]
The [Node.js instructions](https://github.com/nimiq-network/core/blob/master/doc/nodejs-client.md) have been updated in b3ea46bebe0385cf0aa8315a3bdc29cae679a86e.
