### ISSUE TITLE
Synchronization keeps failing if the user's system time is incorrect

### ISSUE THREAD

**Issue by iPLEOMAX** [nimiq-network/core#381]
## New issue checklist

- [x] I have read all of the [`README`](https://github.com/nimiq-network/core/blob/master/README.md) 
- [x] I have searched [existing issues](https://github.com/nimiq-network/core/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s): Latest
- Browser version(s):
- Devices/Simulators/Machine affected: All
- Reproducible in the testnet? (Yes/No): Yes
- Related issues:

#### Expected behavior

> Alert the user that their system time maybe incorrect/off.

#### Actual behavior

> Fails to synchronize and only displays messages in console.

#### Steps to reproduce

> Set your system's time to something few hours or days behind and go to safe or miner page.

#### Crash log? Screenshots? Videos? Sample project?

>...
![nimiq safe - incorrect time desync](https://user-images.githubusercontent.com/7330051/39094899-78d4148a-4648-11e8-9e1c-505adce46835.png)

## Question or Feature Request

> ...

**Comment by styppo** [comment]
The Node.js client now logs an error if the system time appears to be incorrect (thanks @Beeppool). The miner interface now shows a warning as well.
