### ISSUE TITLE
Nimiq developers reference link specified in readme.md returns 404.

### ISSUE THREAD

**Issue by glemiere** [nimiq-network/core#383]
## New issue checklist

- [x] I have read all of the [`README`](https://github.com/nimiq-network/core/blob/master/README.md) 
- [x] I have searched [existing issues](https://github.com/nimiq-network/core/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s):
- Browser version(s):
- Devices/Simulators/Machine affected:
- Reproducible in the testnet? (Yes/No): 
- Related issues:

#### Expected behavior
Returning the web page
> ...

#### Actual behavior
Returns 404
> ...

#### Steps to reproduce
https://nimiq.com/developer-reference
> ...

#### Crash log? Screenshots? Videos? Sample project?

>...

## Question or Feature Request

> ...

**Comment by styppo** [comment]
Fixed in b3ea46bebe0385cf0aa8315a3bdc29cae679a86e

**Comment by glemiere** [comment]
Awesome!
