### ISSUE TITLE
Implement GPU-based mining

### ISSUE THREAD

**Issue by styppo** [nimiq-network/core#39]

**Comment by deniss-muhla** [comment]
About GPU mining and WebGL. I think a lot of users will use their laptops and if they have second discrete video card nvidia and amd windows drivers will block FF and Chrome to use it. It should work if you create electron (or similar) build and add instruction how to enable max performance in drivers settings for this users.
btw awesome project! )

**Comment by sergormo** [comment]
+1
Nice project, already mining. ;)

**Comment by leeola** [comment]
Is there any information about which GPUs this will work for? Eg, is it tailored to specifically NVIDIA or Radeon in any way? Or will it be agnostic?

**Comment by styppo** [comment]
We will look at this once we have settled on a PoW hash function.
