### ISSUE TITLE
Causes consensus failure when processing block with null value being passed to BigNumber 'gte'

### ISSUE THREAD

**Issue by KunaniGaming** [nimiq-network/core#421]
https://github.com/nimiq-network/core/blob/ec965858a697ab2b9956420b4fde3ee72b83fd99/src/main/generic/network/connection/PeerChannel.js#L53

Confirming message was successfully parsed before the next successful try causes a state where consensus is never reached. I confirmed this happened by overriding and running in light mode on a fresh run where height=1 (deleted current main-light-consensus folder). On connections to seed peers the error is triggered:

"Error while processing 'block' message from 'random seed server'. 
A TypeError happens when 'gte' is attempted from BigNumber on a null value. I only have a work around by moving the confirmExpectedmessage true to the end of the next try and adding confirmExpectedmessage false after the catch error log.

**Comment by KunaniGaming** [comment]
This bypasses the problem of never reaching consensus with the 'gte' null error but is not a fix to the  problem. @paberr 

`if (!msg) return;

        try {
            await this.fire(PeerChannel.Event[msg.type], msg, this);
            this.fire('message-log', msg, this, Date.now() - start, rawMsg.byteLength);

          // Confirm that message was successfully parsed.
          this._conn.confirmExpectedMessage(type, true);

        } catch (e) {
            Log.w(PeerChannel, `Error while processing '${PeerChannel.Event[msg.type]}' message from ${this.peerAddress || this.netAddress}: ${e}`);

          // Confirm that message arrived but could not be parsed successfully.
          this._conn.confirmExpectedMessage(type, false);
        }`

**Comment by paberr** [comment]
Thanks, I'll take a look at it tomorrow!

**Comment by paberr** [comment]
I found the issue in the light client.

The semantics of this line have changed with the introduction of BigNumber:
https://github.com/nimiq-network/core/blob/fc2e45d682d8ad47aeeb3516fff003c426c6e7e9/src/main/generic/consensus/base/block/BlockUtils.js#L131

The parameter of the function may be null in the light client, if there are not enough blocks to verify the difficulty.
https://github.com/nimiq-network/core/blob/ec965858a697ab2b9956420b4fde3ee72b83fd99/src/main/generic/consensus/base/blockchain/BaseChain.js#L134

While `isValidTarget` previously returned `false` in such cases, it now throws the error.
I will write the appropriate fix for this later today.

**Comment by paberr** [comment]
Can you check whether [paberr/fix-target-check](https://github.com/nimiq-network/core/tree/paberr/fix-target-check) resolves the issue on your side?

**Comment by KunaniGaming** [comment]
@paberr tested on 4 different systems that I was receiving the error on previously and everything works as expected.
