### ISSUE TITLE
errors related to the dns npm package when using TypeScript

### ISSUE THREAD

**Issue by takahser** [nimiq-network/core#443]
## New issue checklist

- [ x ] I have read all of the [`README`](https://github.com/nimiq-network/core/blob/master/README.md) 
- [ x ] I have searched [existing issues](https://github.com/nimiq-network/core/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s): 1.3.1
- Browser version(s): Chrome 69.0.3497.100 (Official Build) (64-bit)
- Devices/Simulators/Machine affected: -
- Reproducible in the testnet? (Yes/No): not related to any net
- Related issues: -

#### Expected behavior

The NIMIQ core lib can be used in TypeScript & VUE.

#### Actual behavior

I added the nimiq core lib `yarn add @nimiq/core` and started the VUE CLI 3 app `yarn serve`.
In the console, I get a warning:

```
 ERROR  Failed to compile with 1 errors                                                                                                                                                                              15:37:02

This dependency was not found:

* dns in ./node_modules/@nimiq/core/dist/node.js

To install it, you can run: npm install --save dns
```

With NPM, I get a different error:

```
Module not found: Error: Can't resolve 'dns' in
        '/Users/sta/repo/imagewallet-frontend/node_modules/@nimiq/core/dist'
```

I tried installing the `dns` package with both NPM and YARN, which resulted in new errors.

- NPM: When starting the app, I'd get an `Uncaught TypeError: Cannot read property 'node' of undefined`
- YARN: error hawk@0.10.2: The engine "node" is incompatible with this module. Expected version "0.8.x"

#### Steps to reproduce

- install vue
- add the nimiq core package
- for more details, see above (Actual behavior)

#### Crash log? Screenshots? Videos? Sample project?

see above (Actual behavior)

## Question or Feature Request

An npm library that is compatible for the frontend.

**Comment by takahser** [comment]
Seems like the nimiq core package is not supported in the frontend (see also: https://github.com/nimiq-network/core/issues/406).

I solved it using CDN (Kudos to @Albermonte).

index.html:

```
<script src="https://cdn.nimiq.com/nimiq.js"></script>
```

*.ts file:

```
// to satisfy the typescript compiler (the Nimiq symbol is global scoped)
declare let Nimiq: any;
```

**Comment by sisou** [comment]
For the correct types, you can use https://www.npmjs.com/package/@nimiq/core-types.
