### ISSUE TITLE
Add newline character to the end of the JSON-RPC response

### ISSUE THREAD

**Issue by rraallvv** [nimiq-network/core#451]
## New issue checklist

- [x] I have read all of the [`README`](https://github.com/nimiq-network/core/blob/master/README.md) 
- [x] I have searched [existing issues](https://github.com/nimiq-network/core/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## Question or Feature Request

I just wanted to suggest adding a newline character to the end of the JSON-RPC response. Currently requesting a JSON-RPC package from the command line breaks the prompt  alignment and pressing the keyboard arrows to show the previous command overrides the result of the request.

It could be simple accomplished changing the code [here](https://github.com/nimiq-network/core/blob/master/clients/nodejs/modules/JsonRpcServer.js#L869-L871) to something like this:

    //...
            if (single && result.length === 1) {
                res.end(JSON.stringify(result[0]).concat('\n'));
            } else if (!single) {
                res.end(JSON.stringify(result).concat('\n'));
            }
    //...

I should point out that the Bitcoin client already adds the newline character to its response, that's how I was able to notice the difference.

**Comment by terorie** [comment]
@rraallvv For performance reasons, I'd recommend doing this:
```js
//...
        if (single && result.length === 1) {
            res.send(JSON.stringify(result[0]));
        } else if (!single) {
            res.send(JSON.stringify(result));
        }
        res.send("\n");
//...
```

Have you filed a Pull Request yet? If not I can do it.

**Comment by rraallvv** [comment]
No, I haven't, please do.

**Comment by terorie** [comment]
Done!
