### ISSUE TITLE
Sending offline transactions from full nodes on behalf of the nano client

### ISSUE THREAD

**Issue by rraallvv** [nimiq-network/core#468]
## New issue checklist

- [x] I have read all of the [`README`](https://github.com/nimiq-network/core/blob/master/README.md) 
- [x] I have searched [existing issues](https://github.com/nimiq-network/core/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## Question or Feature Request

> I was wondering whether we could have a way to get full nodes to send offline transactions on behalf of the nano client?
I was thinking something like a discovery mechanism and some kind of API.
It could be added for instance to mobile wallets as a fallback option in case the nano node can't reach consensus.

**Comment by paberr** [comment]
You can already kind of do that.
When connected to a full node, you can relay the transaction even though consensus is not yet established.

**Comment by rraallvv** [comment]
Thanks for the information, I'm closing this then.
