### ISSUE TITLE
GPU mining

### ISSUE THREAD

**Issue by terorie** [nimiq-network/core#474]
Recently, the community published Argon2d GPU miners in OpenCL and CUDA.
The purpose of this GitHub issue is to collect ideas, concerns and results regarding Nimiq's future with the advent of GPGPU miners.

#### Future

Should Nimiq regard the advent of GPU miners as the natural evolution of a PoW-based blockchain?

Or should we take measures against this though a hard fork? In the case of GPU domination of the global hash rate, browser/CPU mining could become unprofitable.

#### Argon2 parameters

Hashrate is highly affected by the Argon2d memory cost parameter. Increasing it from 512 KB could shift the GPU/CPU hashrate balance in favor of CPUs. Too high values could break browser mining completely on the other hand. Further research is needed on the possibilities and effects here.

For reference, the [Argon2 white paper v1.3](https://www.cryptolux.org/images/0/0d/Argon2.pdf) recommends `2 lanes and 250 MB of RAM` (memory cost) for `Cryptocurrency mining`. (Page 16)

#### Hashrates

Here are some numbers taken from the Telegram chat:

| Device         | Hashrate |
| -------------- | -------- |
| i7-6700k       | 25 kH/s  |
| GTX 1060 (3GB) | 140 kH/s |
| GTX 1060 (6GB) | 160 kH/s |
| RX 580 (8GB)   | 168 kH/s |
| R9 280X        | 180 kH/s |
| GTX 1070 Ti    | 184 kH/s |
| R9 290         | 200 kH/s |
| GTX 1080       | 222 kH/s |
| GTX 1080 Ti    | 332 kH/s |
| RTX 2080       | 370 kH/s |
| Titan Xp       | 400 kH/s |
| Tesla P100     | 470 kH/s |
| RTX 2080 Ti    | 510 kH/s |
| Titan V        | 540 kH/s |
| Tesla V100     | 740 kH/s |

**Comment by paberr** [comment]
Hi, thank you for bringing this up.
Here's my personal opinion on that:
> #### Future
> Should Nimiq regard the advent of GPU miners as the natural evolution of a PoW-based blockchain?

Yes, I actually see the advent of GPU miners as the foreseeable, natural evolution.
There now even are open-source GPU miners available and everyone can use those.
Previously used CPUs are general purpose units and do still have value in itself.

> Or should we take measures against this though a hard fork? In the case of GPU domination of the global hash rate, browser/CPU mining could become unprofitable.
> #### Argon2 parameters
> Hashrate is highly affected by the Argon2d memory cost parameter. Increasing it from 512 KB could shift the GPU/CPU hashrate balance in favor of CPUs. Too high values could break browser mining completely on the other hand. Further research is needed on the possibilities and effects here.
> 
> For reference, the [Argon2 white paper v1.3](https://www.cryptolux.org/images/0/0d/Argon2.pdf) recommends `2 lanes and 250 MB of RAM` (memory cost) for `Cryptocurrency mining`. (Page 16)

I am against a hard fork here. Changing the parameters of Argon2 does not only have an effect on mining, but also verification. While utilising larger parameters can have the effect to reduce the gap between CPU and GPU, it also increases memory consumption to a prohibitive amount for browsers (considering even verification!).
As stated at various other locations, browser mining is only an onboarding/educational tool, which has not been profitable before the advent of GPU mining.

**Comment by terorie** [comment]
> I am against a hard fork here. Changing the parameters of Argon2 does not only have an effect on mining, but also verification. While utilising larger parameters can have the effect to reduce the gap between CPU and GPU, it also increases memory consumption to a prohibitive amount for browsers (considering even verification!).

This is a very good point. Also, I think the first few MB beyond 512 KB of memory cost widens the gap between high-memory GPUs and CPUs, as the state wouldn't fit into the L3 cache of some CPUs anymore. I agree, modifying the memory cost parameter is not worth the hard fork, then. The parallelism and run count parameters of course isn't worth modifying either.

**Comment by terorie** [comment]
Closed as Nimiq 2.0 is arriving soon

**Comment by chovy** [comment]
fyi: I'm getting  945.1 kH/s on a V100. It costs about $120/week and will net me 750nim per day. (about $30). so i'm doing this for a week then shutting it off.
