### ISSUE TITLE
CPUID can cause loading to fail

### ISSUE THREAD

**Issue by terorie** [nimiq-network/core#475]
- Library version(s): v1.4.1

## Bug report

```
$ node index.js
node-telegram-bot-api deprecated Automatic enabling of cancellation of promises is deprecated.
In the future, you will have to enable it yourself.
See https://github.com/yagop/node-telegram-bot-api/issues/319. module.js:652:30

cpuid.node seems to not have been built. Run npm install.
Uncaught exception: Cannot find module '../build/default/cpuid'
```

Under some circumstances, loading the `cpuid-git` (required by mining submodule selection) with some weird version of `yarn` can fail. This error was produced with yarn 1.9.4 loading a simple NodeJS project that just imports `@nimiq/core^v1.4.1`

Failure to load CPUID should never be a fatal error, but cause a switch to the fallback option.

I'll investigate this error more and submit a PR.

## Replication of the error

```bash
#!/usr/bin/env bash

mkdir test-cpuid
cd test-cpuid

yes '' | yarn init
yarn add @nimiq/core

# Pretend cpuid-git didn't build
rm -r node_modules/cpuid-git/build

echo 'require("@nimiq/core");' > index.js
node index.js
```

**Comment by styppo** [comment]
@terorie Merged #476 , thanks 👍
