### ISSUE TITLE
Nano node doesn't start mining once connected to a pool

### ISSUE THREAD

**Issue by rraallvv** [nimiq-network/core#510]
## New issue checklist

- [X] I have read all of the [`README`](https://github.com/nimiq-network/core/blob/master/README.md) 
- [X] I have searched [existing issues](https://github.com/nimiq-network/core/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s):
1.5.0

- Devices/Simulators/Machine affected:
OS: macOS High Sierra 10.13.6
Node.js: node 10.10.0, npm 6.4.1, pnpm 3.1.1

- Reproducible in the testnet? (Yes/No):
I haven't tried in the testnet yet, since I reproduced the issue only when connected to a pool.

#### Expected behavior

> The nano node should start mining once it reaches consensus and it's connected to the pool.

#### Actual behavior

> One the nano node reaches consensus and connects to the pool but it doesn't start mining but showing an error repeatedly.

#### Steps to reproduce

> Create a new file in an empty folder with the contents of this sample file:
>
> **index.js**
>
```javascript
const Nimiq = require("@nimiq/core");

Nimiq.Log.instance.level = "info";

const client = {};

(async () => {
	Nimiq.GenesisConfig.init(Nimiq.GenesisConfig.CONFIGS["main"]);

	let networkConfig = new Nimiq.DumbNetworkConfig();

	consensus = await Nimiq.Consensus.nano(networkConfig);

	walletStore = await new Nimiq.WalletStore();
	const address = Nimiq.Address.fromUserFriendlyAddress("NQ...");
	client.wallet = { address: address };
	const wallet = await walletStore.get(address);
	if (wallet) {
		client.wallet = wallet;
		await walletStore.setDefault(wallet.address);
	}

	client.miner = new Nimiq.NanoPoolMiner(
		consensus.blockchain,
		consensus.network.time,
		address,
		Nimiq.BasePoolMiner.generateDeviceId(networkConfig),
		{}
	);

	consensus.on("established", () => {
		client.miner.connect("us.nimpool.io", 8444);
	});

	consensus.network.connect();

	consensus.on("established", () => {
		client.miner.startWork();
	});

})();
```
>
> Install Nimiq core 1.5.0
>
> 		$ npm install @nimiq/core@1.5.0
>  
> Start the miner
>  
> 		$ node index.js

#### Crash log? Screenshots? Videos? Sample project?

> 		[I 01:00:08] MinerWorkerPool: Using add-on optimized for instruction set: native
> 		[I 01:00:09] PeerAddressSeeder: Got 6 seed peers from https://nimiq.community/seeds.txt (signed)
> 		[I 01:00:22] BaseConsensus: Synced with all connected peers (2), consensus established.
> 		[I 01:00:23] BasePoolMiner: Connected to pool
> 		[E 01:00:23] Miner: TypeError: Cannot read property 'toUserFriendlyAddress' of undefined
> 		[W 01:00:23] Miner: Failed to start work, retrying in 100ms
> 		[E 01:00:23] Miner: TypeError: Cannot read property 'toUserFriendlyAddress' of undefined
> 		[W 01:00:23] Miner: Failed to start work, retrying in 100ms
> 		...

**Comment by rraallvv** [comment]
I think the error that is being thrown in this line of code https://github.com/nimiq/core-js/blob/master/src/main/generic/miner/Miner.js#L182

**Comment by tomkha** [comment]
https://github.com/nimiq/core-js/blob/1f6e0939adf3ee2afdeea09e2e4e437ee802f252/src/main/generic/miner/Miner.js#L183

should be ${block.minerAddr.toUserFriendlyAddress()}

**Comment by jeffesquivels** [comment]
@tomkha good catch, thanks!
